### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

arr = np.random.randint(1, 51, 10)

media = np.mean(arr)

desvio_padrao = np.std(arr)

print('Array: ', arr)
print('Média: ', media)
print('Desvio Padrão: ', desvio_padrao)


Array:  [18  4 38 22 35 22 28 11  8 27]
Média:  21.3
Desvio Padrão:  10.668176976409793


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np

arr = np.random.rand(10)

arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])

print(arr)

[0.68848383 0.58404228 0.66675567 0.90997028 0.60627107 0.27620117
 0.12175354 0.30791908 0.47337025 0.20821033]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np

matriz = np.random.rand(3, 3, 3)

maximos = np.amax(matriz, axis = 1)

print('Matriz original: ', matriz)
print('Valores máximos de cada linha de cada matriz 2D: ', maximos)

Matriz original:
  [[[0.99715016 0.59091866 0.78570277]
  [0.99773955 0.48656013 0.05893097]
  [0.1947392  0.31569114 0.06585222]]

 [[0.33227373 0.54193251 0.00829482]
  [0.31254508 0.65263579 0.14152193]
  [0.3039018  0.25056565 0.55781059]]

 [[0.34144882 0.40002345 0.60817594]
  [0.09915696 0.54112489 0.32286677]
  [0.75423263 0.48936533 0.23403123]]]
Valores máximos de cada linha de cada matriz 2D:
  [[0.99773955 0.59091866 0.78570277]
 [0.33227373 0.65263579 0.55781059]
 [0.75423263 0.54112489 0.60817594]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np

matriz = np.random.rand(5, 5)

media = np.mean(matriz, axis = 1)
matriz_linha_media = matriz - media[:, np.newaxis]

print('Matriz original:\n', matriz)
print('Média:\n', media)
print('Matriz com a média de cada linha subtraída:\n', matriz_linha_media)

Matriz original:
 [[0.886557   0.6019194  0.8095658  0.30977495 0.60233013]
 [0.87704866 0.66997284 0.81099664 0.77346526 0.90102879]
 [0.75543492 0.20852539 0.85944087 0.86986696 0.59588667]
 [0.44362679 0.9895214  0.30217589 0.80304143 0.82328687]
 [0.91262807 0.78308868 0.57864024 0.25523869 0.57733474]]
Média:
 [0.64202946 0.80650244 0.65783096 0.67233048 0.62138608]
Matriz com a média de cada linha subtraída:
 [[ 0.24452754 -0.04011006  0.16753635 -0.3322545  -0.03969933]
 [ 0.07054622 -0.1365296   0.00449421 -0.03303718  0.09452635]
 [ 0.09760395 -0.44930557  0.2016099   0.212036   -0.06194429]
 [-0.22870368  0.31719092 -0.37015459  0.13071096  0.15095639]
 [ 0.29124199  0.1617026  -0.04274585 -0.36614739 -0.04405135]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np

matriz = np.random.rand(4, 4)

diag_princ = np.diag(matriz)
diag_sec = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_princ, diag_sec])
std_diag = np.std([diag_princ, diag_sec])

print('Matriz:\n', matriz)
print('Diagonal principal:\n', diag_princ)
print('Diagonal secundária:\n', diag_sec)
print('Media diagonal:\n', media_diag)
print('Desvio pdrão das diagonais:\n', std_diag)

Matriz:
 [[0.61995985 0.9588836  0.75920591 0.31475369]
 [0.46166786 0.36636079 0.50707755 0.10399267]
 [0.7828896  0.00390911 0.34820446 0.24110374]
 [0.12925932 0.43559717 0.94083307 0.22597894]]
Diagonal principal:
 [0.61995985 0.36636079 0.34820446 0.22597894]
Diagonal secundária:
 [0.31475369 0.50707755 0.00390911 0.12925932]
Media diagonal:
 0.31443796366451726
Desvio pdrão das diagonais:
 0.18467342345914947
